# 자료형

In [ ]:
a=10
# 변수 지우기

# 표준입력장치로 실수를 입력받아서 정수로 변환하기

# 표준출력장치
# 문자열 - %?
# 정수 - %?
# 실수 - %?

# 외부상수받기
name = "홍길동"
age=25
tall=175.456
# 이름:홍길동, 나이:25, data:175.45 로 출력되게 하는 3가지 방법

# 변수를 만들때 3가지 방법
# camelcase를 camel표기법으로
# snakecase를 snake표기법으로
# pascalcase를 pascal표기법으로

# 여러줄의
# 문장을
# 한번에 변수에 넣기

string = "Life is too short, You need python"
# 인덱싱으로 f 추출하기
# 인덱싱으로 short 추출하기
# 인덱싱으로 life 추출하기
# 인덱싱으로 python 추출하기
# d가 몇번째에 있는지 확인하는 방법
# d의 인덱스 번호 확인
# ['Life', 'is', 'too', 'short,', 'You', 'need', 'python'] 가 반환되게

# 대문자로
# 소문자로

abc = 'abcdefg'
# 'a,b,c,d,e,f,g' 반환되게
# 이어서 ['a', 'b', 'c', 'd', 'e', 'f', 'g'] 가 반환되게

hz = "홀짝홀짝홀짝"
# 홀홀홀 반환되게

# 표준입력장치로 사용자의 영문이름을 한번에 입력받아서 성과 이름 순서를 바꾸어 출력하는 프로그램을 작성
# hong gildong -> gildong hong (2가지 방법)

# 이스케이프 문자
# 'c:\python38\test' 출력하는 법 (2가지 방법)

# ', " 를 문자로 인식하는 법
# "naver", "kakao", "sk", "samsung" 를
# naver/kakao/sk/samsung 반환해주는 프린트 문 작성


# 자료형태

In [ ]:
a1=[1,4,3,2]

# 5를 추가
# 4와 3사이에 5추가 (2가지 방법)
# 4 제거 (2가지 방법)
# a1에 5가 몇개인지 보는 방법

# 역순으로 추출되게 [5,2,3,5,4,1]
# 오름차순 정렬
# 내림차순 정렬

a2=[1,2,3]

# [1,2,3,[4,5,6,7]]으로 출력 (2가지 방법)
# a2의 원소의 개수
# 3의 인덱스 번호 추출

wishlist = ['가방', '시계', '신발']
# mycart라는 새로운 리스트를 만들고 시계와 신발을 추출
# wishlist 시계랑 신발은 삭제 (2가지 방법)

a3 = [4,5,6]
# a3 언패킹 : x, y, z 에 각각 4, 5, 6 할당하기

movie_rank = ['닥터스트레인지', '스프릿', '럭키']
# 배트맨을 추가
# 슈퍼맨을 닥터스트레인지와 스프릿 사이에 넣으세요 (2가지 방법)

# 튜플을 1~10까지 만들고 짝수만 슬라이싱하여 출력
# (2,4,6,8,10)

apart1 = [[101, 102],[201, 202],[301, 302]]
# 101호
# 102호
# ...
# 302호

lst = [1,2,3,4,5,3,4,5]
# 항목수
# 합계
# 최소값
# 최대값
# 3의 개수
# 평균 (계산식)

s1 = set([1,2,3,4,5,6])
s2 = set([4,5,6,7,8,9])

# 교집합 (2가지 방법)
# 합집합 (2가지 방법)
# 차집합 (2가지 방법, 2가지 버전)

s3 = set([1,2,3])

# 원소 4 추가
# 5,6,7 한번에 추가
# 7제거 (2가지 방법 - 한개 방법은 없는 값을 지우려해도 오류가 뜨지 않음)

# 딕셔너리 만드는 3가지 방법
# {'김밥': 3000, '떡볶이': 2000, '어묵': 3500, '튀김': 2800}

alphabet={'a':'apple','b':'banana','c':'car','e':'error'}
# e,error 제외시키기
# 키 c의 값 cool로 변경
# 키 d와 값 dog 추가

# 키 a의 값 확인 (기본)
# 원소에 없는 키 f의 값 확인 시 오류가 안뜨게 확인하는 법
# 원소에 없는 키 f의 값 확인 시 오류가 안뜨게 하되, food가 추출되게 (단, alphabet 내용은 변하지 않게)
# 원소에 없는 키 f의 값 확인 시 alphabet에 키 f가 추가되고 값은 food로 넣는 방법

# alphabet의 키 추출
# alphabet의 값 추출
# alphabet의 키와 값 둘다 추출
# alphabet의 한번에 모든 내용 삭제

charset = ['abc', 'code', 'band', 'band', 'abc']
# wc = {'abc':2, band:2, code:1} 가 추출되게


# 조건문 반복문

In [ ]:
# 표준입력장치로 점수를 입력받아서
# 100~90점 A
# 89~80점 B
# 79~70점 C
# 70점 이하 F
# 출력하는 조건문을 만드시오

pokect = ['paper', 'cellphone', 'money']
# 만약에 주머니에 돈이 있으면 택시를 타고 없으면 걸어가라

# 출생 연도를 표준입력장치로 받아서
#     ~1924 가장 위대한 세대(The Greatest Generation)
# 1925~1945 침묵 세대(The Silent Generation)
# 1946~1964 베이비 부머(baby boomer)
# 1965~1980 X세대(Generation X)
# 1981~1996 밀레니얼(millennial)
# 1997~     Z세대(Generation Z)
# 당신의 세대는 00 세대입니다. 출력

# 길이, 부피, 무게나 금액을 표기할 때 1000을
# 'k'로 표기하곤 합니다. 입력은 10의 n제곱 입력하세요.
# 예를 들어, 3000m는 3km로 표기하는 것이 일반적입니다.
# 다음은 입력받은 숫자가 1000보다 크면 1자리부터
# 100자리까지의 숫자를 생략하고 'k'를 붙여주는
# 파이썬 코드입니다.
# 1000이하의 10의 n제곱을 입력하면 아무것도 수행하지 않음

# 숫자를 입력받아서 10의 배수면 프로그램 종료가 되도록 while문으로 코딩
# 11, 5676 다시입력하세요
# 110 종료
# 10의 배수가 아닌 입력받은 변수들은 리스트에 추가하여 최종 반환

# 'q'를 입력할때까지 이름을 입력받기
# q를 입력받기 전까지 입력한 내용을 리스트에 추가하여 최종 반환

# 1. 게임을 한계를 주도록 3번 이내에 맞추지 못하면 'You Lose'
# 2. 3번 내에 맞추면 'You Win!'
# 값을 바로 적용시키기 보다는 변수에 할당하는 것이 좋음

# id = 'id123', pwd = 'pwd123'
# while문으로 아이디와 패스워드를 입력받아서 id가 틀리면 id를 확인하세요
# pwd가 틀리면 pwd를 확인하세요

# 구구단 만들기
# -----[2단]-----
# 2*1=2
# 2*2=4

# while문으로 1~10의 합 구하기
# for문으로 1~10의 합 구하기

# 1. ['a','b','c']를 for 문을 사용해서 전부 대문자로 ['A','B','C']
# 2. ['dog', 'cat', 'parrot'] 첫글자만 출력 d, c, p
# 3. ['I', 'study', 'python', 'language', '!']중에서 3글자 이상인 원소 출력
# 4. 1~10까지 숫자중 모든 홀수의 합을 출력하는 for 문을 작성 1+3+5...9=합

# my_list=['가','나','다','라','마']
# 가 나
# 나 다
# 다 라
# 라 마

# if 문을 활용해서 가위바위보 게임 만들기
# 변수 가위, 바위, 보, 이겼다, 졌다, 비겼다, 나의변수, 컴퓨터변수
# if else만 사용해서

#1. elif로 다중조건문을 변환하시오
#2. mine을 표준입력장치로 변경해주세요.
#3. yours도 가위, 바위, 보를 랜덤하게 나오도록 업그레이드
#4. mine에 q를 누르면 게임 종료되도록
#5. 잘못입력한경우 잘못입력했다고 표시

# 1 ~ 100 30
# 내가 50! 다운!
# 20 업
# 업앤다운 게임을 만들어보세요
# 게임 횟수 제한

# 1~100 사이에서
# 5의 배수이면서(and) 3의 배수가 아닌 합 계산하기

#a=[1,2,3,4]
# 3을 곱하고 짝수만 result3에 넣는 코드를 작성하세요.
# [6, 12]
# for문과 리스트 내포 2가지 방법

# 구구단 코드 [2,4,6,8....3,6,9,......81]
# 리스트 내포로 만드시오.

# 클래스

In [ ]:
# 참치선물세트 속성 : 일반, 야채, 고추
# 출력 메서드
# 특별세트 (상속)
# 속성 : 일반, 햄, 카놀라유
# 출력 메서드

# 세면도구 속성 : 치약, 샴푸, 비누
# 내용물출력 메서드
# 특별세트 (상속)
# 속성 : 치약, 샴푸, 비누, 면도기
# 내용물출력 메서드

# 자동차 클래스와 객체
# 속성 : brand, model, color
# 메소드 : drive - 주행중입니다 출력
# 메소드 : trun_on - 시동을 켭니다 출력
# 메소드 : trun_off - 시동을 끕니다 출력

#1. car class 만들기
# 속성 : name, cc, year
# check 메소드를 만들고 cc가 1000미만이면 소형, 1000~2000이면 중형, 2000~ 대형
# car 객체를 만들때 car_count 개수가 하나씩 증가하도록
# car1 소나타, 2500, 2019 --> 대형 이고 car_count 실행시키면 1대
# car2 아반테, 1500, 2018 --> 중형 이고 car_count 실행시키면 2대

# car1의 이름을 확인할 수 있는 getName 메소드와
# 이름을 변경할 수 있는 setName 메소드를 추가해서 이름을 바꿔보세요.
# car1의 소나타 getName로 확인 후에 setName으로 '모닝'으로 변경하는 클래스

# 1. Character 클래스 만들기
# Character의 속성값에 Health 속성 ( 생성시 200 )
# Character 클래스 move() 메소드를 추가하고 메소드 사용시 health가 -10이 됨
# Character의 클래스 rest() 메소드를 추가하고 메소드 사용시 health +10이 됨
# 현재 health를 알 수 있는 checkHealth() method를 추가

# 2. Knight, Healer 클래스 만들기
# Knight와 Healer는 Character의 클래스를 상속
# Knight Move()를 하면 Health가 추가로 -5를 더 소모함
# Knight Attack()를 추가하고 '공격합니다.'라는 메소드를 작성

# Healer Mana라는 속성을 추가하고 생성시 100의 값을 주어짐
# Healer heal() 메소드를 추가하고 이 메소드는 Character들을 매개변수로 받음
# Healer heal() 메소드를 실행하면 Mana 가 -10이 되고
# 전달받은 Character 객체에 rest() 메소드가 실행되어 +10이 되도록 함
# Healer는 현재 마나 속성을 확인할 수 있는 Checkmana() 메소드를 추가

# 속성 : 계좌번호 '123456' (ano) / owner : 이름 (문자열) / 잔액 : balance, 비공개 속성
# method : 저금(deposit), 출금(withdraw), 조회 출력이 가능하게
# 저금(deposit) : 1000만원 이상 입금할 수 없음 (통장 최대 1000만원 한도)
# 출금(withdraw) : 잔액이 0이면 출금이 안되도록
# 조회 출력이 가능하게

#  def check_duplicate(ano)
# 사용자로부터 필요한 정보를 입력받아서 계좌 생성 - def create_account()
# 사용자로부터 필요한 정보를 입력받아서 계좌에 돈을 입금 - def deposit_account()
# 사용자로부터 필요한 정보를 입력받아서 계좌에 돈을 출금 - def withdraw_account()
# 화면 만들기
# '1:계좌생성, 2:계좌목록, 3:입금, 4:출금, 5:종료>'


# Numpy

In [ ]:
import numpy as np
# [1,4,5,8] 각 원소가 실수형인 배열 생성
# 원소의 타입과 몇 by 몇인지 확인

# Vector (1차원) 생성 [1,2,3,4]
# Matrix (2차원) 생성 [[1,2,3],[4,5,6]]
# Tensor (3차원) 생성 [[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
#                     [[13,14,15,16],[17,18,19,20],[21,22,23,24]]]

# [1,2,3] 각 원소의 타입이 float32, int8 인 배열 각각 생성

# Matrix
# 1차원 벡터로 변경 (2가지 방법)
# (3 by 2) 2차원 매트릭스로 변경
# 3 혹은 2만 사용해서 (3 by 2) 2차원 매트릭스로 변경
# 원소 5를 추출

# Tensor
# 원소 19 추출

# a = np.arange(16).reshape(4,-1)
# 결과값
# [[5,6],
#  [9,10]]

# [[5,6,7],
#  [9,10,11]]

# [[1,3],
#  [9,11]]

# x 는 앞에 3열
# y 는 마지막 열
# shape로 결과값을 보면
# x.shape ==> (4,3)
# y.shape ==> (4,)

# 배열 만들어서 다음 출력값이 나오게
# array([1, 3, 5, 7, 9])
# array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])
# 바로 윗줄 배열을 리스트 형태로 변환

# -2부터 2까지 401등분한 배열 만들기
# (2,4) 행렬을 1로 다 채우기 (정수형으로)
# (2,4) 행렬을 0으로 다 채우기 (실수형으로)

# b = np.arange(12).reshape(3,4)
# 원본 배열을 유지하면서 원소 값을 1로 다 바꾸기
# 원본 배열을 유지하면서 원소 값을 0으로 다 바꾸기

# 대각선이 1인 3 by 3 정방행렬 만들기 (원소는 정수형으로) (2가지 방법)
# 출력값
# array([[0, 0, 1, 0, 0],
#        [0, 0, 0, 1, 0],
#        [0, 0, 0, 0, 1]], dtype=int32)

# array([[0., 0., 0.],
#        [1., 0., 0.],
#        [0., 1., 0.],
#        [0., 0., 1.]])

# c = np.arange(9).reshape(3,3)
# 대각선 위치의 값을 추출 array([0, 4, 8])
# array([1, 5])

# np.random.seed(seed=1000) # 시드로 난수 생성 초기값 지정
# np.random.uniform(0, 1, 10).reshape(2,5) # 균등 분포 # 최소 최대 개수
# np.random.normal(0, 1, 10).reshape(2,5) # 정규 분포 # 평균 표준편차 개수
# np.random.binomial(n, p, size) # 이항 분포
# np.random.poisson(lam. size) np # 포아송 분포
# np.random.standard_t(df, size) np # t-분포
# np.random.f(dfnum, dfden, size) # F-분포

# d = np.arange(1,13).reshape(3,4)
# 모든 원소의 합
# 모든 행들의 합 array([10, 26, 42])
# 모든 열들의 합 array([15, 18, 21, 24])

# e = np.arange(1, 25).reshape(2,3,4)
# 모든 원소의 합
# array([[14, 16, 18, 20],
#        [22, 24, 26, 28],
#        [30, 32, 34, 36]])
# array([[15, 18, 21, 24],
#        [51, 54, 57, 60]])
# array([[10, 26, 42],
#        [58, 74, 90]])

# f = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
# 정렬 (자기 자신 바뀌지 않는 버전)
# array([[ 3,  4,  5,  7],
#        [ 1,  9, 11, 12],
#        [ 1,  2,  5, 14]])

# array([[ 1,  3,  1,  7],
#        [ 2,  5,  5,  9],
#        [ 4, 12, 11, 14]])

# 정렬 (변수를 지정하지 않아도 한번 수행하면 f에 할당되는 정렬)

# g = np.array([42,38,12,25])
# 정렬된 [12 25 38 42] 순으로 원래 데이터 g의 인덱스 번호 추출
# 인덱스 순서대로 원래 데이터 가져와서 정렬
# 내림차순

# 통계 수학 함수
# 합
# 평균
# 분산
# 표준편차
# 밑이 자연상수 e인 지수함수

# h1 = np.arange(1,5).reshape(2,2)
# h2 = np.arange(5,7).reshape(1,2)
# 출력 (2가지 방법씩)
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

# array([[1, 2, 5],
#        [3, 4, 6]])
# h1과 h2 내적 (2가지 방법)

# i = np.array([1,3,0], float)
# a>1 이 참이면 10, 거짓이면 0을 반환
# a>1 이 참인 경우 index 값을 반환

# j = np.array([np.Inf, np.NaN, 1, np.nan, np.inf, np.NAN])
# nan 개수

# k = np.array([1,2,4,5,8,78,23,3])
# 제일 큰 78의 인덱스값 반환 (최대값 반환)
# 제일 작은 1의 인덱스값 반환 (최소값)

# l = a.reshape(2, -1)
# 출력
# array([3, 1])
# array([0, 3])
# array([1, 1, 1, 0])
# array([0, 0, 0, 1])

# m = np.array([1,2,4,5,8,78,23,3])
# a가 4보다 큰 값만 나옴 (참인 값만 반환)

# n1 = np.array([2,4,6,8])
# n2 = np.array([1,3,2,0,0,1])
# n2 각 원소의 인덱스 값을 가진 n1 반환 (2가지 방법)

# o1 = np.arange(1,13).reshape(3,4)
# o2 = np.array([1,2,0,1])
# o3 = np.array([2,1,3,0])
# 매트릭스 , o2,o3 각 원소의 인덱스 값을 가진 o1 반환


# 사분위수
# 최소값
# 1사분위수
# 2사분위수
# 3사분위수
# 최대값

In [ ]:
import numpy as np

In [ ]:
# [1,4,5,8] 각 원소가 실수형인 배열 생성
# 원소의 타입과 몇 by 몇인지 확인

hw1 = np.array([1,4,5,8],dtype=float)
print(hw1)
print(type(hw1), hw1.shape)

[1. 4. 5. 8.]
<class 'numpy.ndarray'> (4,)


In [ ]:
# Vector (1차원) 생성 [1,2,3,4]
# Matrix (2차원) 생성 [[1,2,3],[4,5,6]]
# Tensor (3차원) 생성 [[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
#                     [[13,14,15,16],[17,18,19,20],[21,22,23,24]]]

vector = np.arange(1,5)
print(vector)

matrix = np.arange(1,7).reshape(2,3)
print(matrix)

tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
# [1,2,3] 각 원소의 타입이 float32, int8 인 배열 각각 생성
hw2 = np.array([1,2,3],dtype=np.float32)
print(hw2)

hw3 = np.array([1,2,3], dtype=np.int8)
print(hw3)

[1. 2. 3.]
[1 2 3]


In [ ]:
# Matrix
# 1차원 벡터로 변경 (2가지 방법)
hw4 = matrix.reshape(-1,)
print(hw4)

hw5 = matrix.flatten()
print(hw5)

# (3 by 2) 2차원 매트릭스로 변경
hw6 = matrix.reshape(3,2)
print(hw6)

# 3 혹은 2만 사용해서 (3 by 2) 2차원 매트릭스로 변경
hw7 = matrix.reshape(3,-1)
hw8 = matrix.reshape(-1,2)
print(hw7)
print(hw8)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Matrix
# 원소 5를 추출
print(matrix[-1,1])

# Tensor
# 원소 19 추출
print(tensor[1,1,2])

5
19


In [ ]:
a = np.arange(16).reshape(4,-1)
print(a)

# 결과값
# [[5,6],
#  [9,10]]

# [[5,6,7],
#  [9,10,11]]

# [[1,3],
#  [9,11]]

print(a[1:3,1:3])
print(a[1:3,1:])
print(a[0::2,1::2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  6]
 [ 9 10]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 1  3]
 [ 9 11]]


In [ ]:
# x 는 앞에 3열
# y 는 마지막 열
# shape로 결과값을 보면
# x.shape ==> (4,3)
# y.shape ==> (4,)

x = a[:-1,].reshape(4,3)
print(x)
print(x.shape)

y = a[-1,]
print(y)
print(y.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
[12 13 14 15]
(4,)


In [ ]:
# 배열 만들어서 다음 출력값이 나오게
# array([1, 3, 5, 7, 9])
# array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])
# 바로 윗줄 배열을 리스트 형태로 변환

hw9 = np.arange(1,10,2)
print(hw9)

hw10 = np.arange(0,5.1,0.5)
print(hw10)

[1 3 5 7 9]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [ ]:
# -2부터 2까지 401등분한 배열 만들기

hw11 = np.linspace(-2,2,401)
print(len(hw11))

401


In [ ]:
# (2,4) 행렬을 1로 다 채우기 (정수형으로)
# (2,4) 행렬을 0으로 다 채우기 (실수형으로)

hw12 = np.ones((2,4), dtype=np.int8)
print(hw12)

hw13 = np.zeros((2,4), dtype=np.float32)
print(hw13)

[[1 1 1 1]
 [1 1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
b = np.arange(12).reshape(3,4)
print(b)
# 원본 배열을 유지하면서 원소 값을 1로 다 바꾸기
# 원본 배열을 유지하면서 원소 값을 0으로 다 바꾸기

hw14 = np.ones_like(b)
hw15 = np.zeros_like(b)

print(hw14)
print(hw15)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
# 대각선이 1인 3 by 3 정방행렬 만들기 (원소는 정수형으로) (2가지 방법)

hw16 = np.identity(3, dtype=np.int8)
print(hw16)

hw17 = np.eye(3,3, dtype=np.int8)
print(hw17)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# 출력값
# array([[0, 0, 1, 0, 0],
#        [0, 0, 0, 1, 0],
#        [0, 0, 0, 0, 1]], dtype=int32)

hw18 = np.eye(3,5,k=2,dtype=np.int8)
print(hw18)

# array([[0., 0., 0.],
#        [1., 0., 0.],
#        [0., 1., 0.],
#        [0., 0., 1.]])

hw19 = np.eye(4,3,k=-1,dtype=np.float32)
print(hw19)

[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# c = np.arange(9).reshape(3,3)
# 대각선 위치의 값을 추출 array([0, 4, 8])
# array([1, 5])

# np.random.seed(seed=1000) # 시드로 난수 생성 초기값 지정
# np.random.uniform(0, 1, 10).reshape(2,5) # 균등 분포 # 최소 최대 개수
# np.random.normal(0, 1, 10).reshape(2,5) # 정규 분포 # 평균 표준편차 개수
# np.random.binomial(n, p, size) # 이항 분포
# np.random.poisson(lam. size) np # 포아송 분포
# np.random.standard_t(df, size) np # t-분포
# np.random.f(dfnum, dfden, size) # F-분포

# d = np.arange(1,13).reshape(3,4)
# 모든 원소의 합
# 모든 행들의 합 array([10, 26, 42])
# 모든 열들의 합 array([15, 18, 21, 24])

# e = np.arange(1, 25).reshape(2,3,4)
# 모든 원소의 합
# array([[14, 16, 18, 20],
#        [22, 24, 26, 28],
#        [30, 32, 34, 36]])
# array([[15, 18, 21, 24],
#        [51, 54, 57, 60]])
# array([[10, 26, 42],
#        [58, 74, 90]])

# f = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
# 정렬 (자기 자신 바뀌지 않는 버전)
# array([[ 3,  4,  5,  7],
#        [ 1,  9, 11, 12],
#        [ 1,  2,  5, 14]])

# array([[ 1,  3,  1,  7],
#        [ 2,  5,  5,  9],
#        [ 4, 12, 11, 14]])

# 정렬 (변수를 지정하지 않아도 한번 수행하면 f에 할당되는 정렬)

# g = np.array([42,38,12,25])
# 정렬된 [12 25 38 42] 순으로 원래 데이터 g의 인덱스 번호 추출
# 인덱스 순서대로 원래 데이터 가져와서 정렬
# 내림차순

# 통계 수학 함수
# 합
# 평균
# 분산
# 표준편차
# 밑이 자연상수 e인 지수함수

# h1 = np.arange(1,5).reshape(2,2)
# h2 = np.arange(5,7).reshape(1,2)
# 출력 (2가지 방법씩)
# array([[1, 2],
#        [3, 4],
#        [5, 6]])

# array([[1, 2, 5],
#        [3, 4, 6]])
# h1과 h2 내적 (2가지 방법)

# i = np.array([1,3,0], float)
# a>1 이 참이면 10, 거짓이면 0을 반환
# a>1 이 참인 경우 index 값을 반환

# j = np.array([np.Inf, np.NaN, 1, np.nan, np.inf, np.NAN])
# nan 개수

# k = np.array([1,2,4,5,8,78,23,3])
# 제일 큰 78의 인덱스값 반환 (최대값 반환)
# 제일 작은 1의 인덱스값 반환 (최소값)

# l = a.reshape(2, -1)
# 출력
# array([3, 1])
# array([0, 3])
# array([1, 1, 1, 0])
# array([0, 0, 0, 1])

# m = np.array([1,2,4,5,8,78,23,3])
# a가 4보다 큰 값만 나옴 (참인 값만 반환)

# n1 = np.array([2,4,6,8])
# n2 = np.array([1,3,2,0,0,1])
# n2 각 원소의 인덱스 값을 가진 n1 반환 (2가지 방법)

# o1 = np.arange(1,13).reshape(3,4)
# o2 = np.array([1,2,0,1])
# o3 = np.array([2,1,3,0])
# 매트릭스 , o2,o3 각 원소의 인덱스 값을 가진 o1 반환


# 사분위수
# 최소값
# 1사분위수
# 2사분위수
# 3사분위수
# 최대값

# 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
# 10 20 30 40
# 50 60 70 80

# m2 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9],[10, 11, 12, 13, 14]])
# 1) 이 행렬에서 값 7 을 인덱싱한다. 
# 2) 이 행렬에서 값 14 을 인덱싱한다.
# 3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
# 4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
# 5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

#2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
# 1) 이 배열에서 3의 배수를 찾아라.
# 2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
# 3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

# 값을 직접 입력하지 말고
# 우측의 행렬을 만드시오.
# 2, 1, 0, 0, 0
# 3, 2, 1, 0, 0
# 0, 3, 2, 1, 0
# 0, 0, 3, 2, 1
# 0, 0, 0, 3, 2

# 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에
# 대해 다음과 같은 값을 구하시오.
# 1) 전체의 최댓값
# 2) 각 행의 합
# 3) 각 행의 최댓값
# 4) 각 열의 평균
# 5) 각 열의 최솟값

# 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은
# 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.
# array([[ 1,   2,   3,  4],
#        [ 46, 99, 100, 71],
#        [ 81, 59, 90, 100]])
# 결과값 
# [[  3   2   4   1]
#  [100  99  71  46]
#  [ 90  59 100  81]]

# 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고,
# 던져서 나오는 숫자의 평균을 구하시오.

# 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고
# 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.

# Pandas

In [ ]:
import pandas as pd
import numpy as np


dict_data = {"a":1, "b":2, "c":3}
# 딕셔너리를 시리즈 형태로 변환
# 인덱스와 값 확인

list_data = ['영인','2010-05-01', '여', 14, True]
# 리스트를 시리즈 형태로 변환
# 인덱스는 '이름','생년월일','성별', 나이, '학생여부' 로 지정
# 여 인덱싱 (2가지 방법)
# 여러개 원소 영인, 14 인덱싱 (2가지 방법)

# 시리즈 만들기
# 서울 9904312
# 부산 3448737
# 인천 2890451
# 대구 2466052

# 3448737 만 인덱싱 (2가지 방법)
# 3448737 와
# 2466052 두개 인덱싱 (2가지 방법)

import seaborn as sns
iris = sns.load_dataset('iris')

# 각 열의 원소 개수 확인
# species 열의 종류 확인
# species 열의 종류별 값 개수 확인

# sr = pd.Series([9904312,3448737,2890451,2466052], index=["서울","부산","인천","대구"])
# 데이터의 전체 합 구하기
# 데이터의 전체 평균 구하기
# 오름차순 정렬
# 내림차순 정렬

dict_data = {'c0':[1,2,3],'c1':[4,5,6],'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,15]}
# 딕셔너리를 데이터프레임 형태로 변환

list_data=[[15,'남','신촌중'],[17,'여','연세중']]
# 리스트를 데이터프레임 형태로 변환
# 인덱스는 준서 예은
# 열 이름은 나이 성별 학교
# 인덱스 이름과 열 이름 확인하기
# 인덱스 학생1 학생2 로 변경
# 열 이름 연령 남여 소속 으로 변경
# 메소드를 사용해서 행과 열이름 변경
# 인덱스 학생1을 학생3으로
# 열이름 소속을 비고로

# numpy random.randint를 사용해서 60~100 사이 16개 숫자를 만들고
# reshape하고 index가 james, maria, brian, alice를 만들고
# 컬럼이름은 kor, eng, math, music로 된 데이터 프레임을 생성하기

# 변수 복사하기 (2가지 방법)

# brian 행 삭제
# james, maria 행 한번에 삭제

# eng 열 삭제
# kor, music 열 한번에 삭제

# 원본 데이터에서 maria 행 뽑아오기 (2가지 방법)
# brian과 alice 행 한번에 뽑아오기 (2가지 방법)
# maria와 brian 슬라이싱으로 행 뽑아오기 (2가지 방법)

# math 열 뽑아오기
# math와 music 열 뽑아오기
# math 열만 뽑되, 데이터프레임 형식으로 뽑기

# maria 음악점수 가져오기 (2가지 방법)
# james의 영어 수학 음악점수 가져오기 (2가지 방법)
# 마리아~엘리스 영어~음악까지 가져오기 (2가지 방법)

# gym 열 추가하고 값은 90으로 통일
# gildong 행 추가하고 값은 90,70,60,75,60으로

# 인덱스 순서를 James maria gildong brian alice 순으로 변경

# exam_data = {'이름':['길동','철수','영희'], '수학':[90, 80, 70],
#             '영어':[98,89,95], '음악':[85,95,100], '체육':[100,90,90]}
# df = pd.DataFrame(exam_data)
# 이름을 인덱스로 지정
# 인덱스로 지정된 이름을 열로 변환

# dict_data = {'c0':[1,2,3],'c1':[4,5,6],'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,15]}
# df = pd.DataFrame(dict_data, index=['r0','r1','r2'])
# 인덱스를 r0 r1 r2 r3 r4로 새로 지정해서 행 추가 후 값은 0으로 채우기
# 행 인덱스 내림차순 정렬
# 열 c1 기준으로 내림차순 정렬

# student1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
# student2 = pd.Series({'수학':80,'국어':90,'영어':80})
# np.nan 결측값을 0으로 처리해서 사칙 연산 + - * /

# import seaborn as sns
# titanic = sns.load_dataset('titanic')
# 열 age fare만 뽑기

# csv 파일 만들기
# %%writefile sample.csv
# c1,c2,c3
# 1,1.15,one
# 2,2.23,two
# 3,3.32,three

# csv 파일 불러오기 (excel, json, html 등 같은 구조)
# c1 c2 c3 가 열 이름이 아닌 첫번째 행으로 되게 불러오기
# 1,1.15,one 가 열이름, 첫번쨰 행 2,2.23,two 으로 되게 불러오기
# c1을 인덱스로 잡히게 불러오기
# 데이터를 csv로 저장 (excel, json, html 등 같은 구조)

# mpg.csv 불러오기 (열 이름 없는 구조 주의)
# df.columns = ['mpg', 'cylinders', 'displacement','horsepower','weight',
#               'acceleration','model year', 'origin', 'name']

# 첫 5개 행 출력
# 끝 5개 행 출력
# 행의 개수와 열의 개수 확인
# 데이터의 정보 확인 (열이름, 결측값 아닌 값 개수, 타입 등 한번에 나오는것)
# 데이터프레임 기술통계 정보 확인
# 각 열이 가지고 있는 값의 개수 확인
# origin 열의 종류 확인
# origin 열의 종류별 값 개수 확인

# mpg 열의 평균, 중앙값, 최소값, 최대값, 표준편차 각각 구하기

# 데이터의 상관계수 한번에 확인
# 특정 열 mpg 와 weight의 상관계수 확인

# 남북한발전전력량.xlsx 불러오기
# 1990년도부터 남한과 북한의 합계 행 2개만 가져오기
# 행 인덱스를 south와 north로 변경
# 열 이름을 정수형으로 변경
# 행과 열 서로 바꾸기
# 그래프 그리기
# 막대그래프로 그리기

# 시각화

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# mpg 데이터 불러오기
# df.columns = ['mpg', 'cylinders', 'displacement','horsepower','weight',
#               'acceleration','model year', 'origin', 'name']

# 기본 내장 시각화

# weight와 mpg 의 산점도
# mpg와 cylinders 의 boxplot
# mpg의 히스토그램 그리기
# 구간 = 10, 색 지정, 그림 사이즈 10,5

# 산점도 scatter 그리기
# x축 weight, y축 mpg / 색 지정, 동그라미 크기 10, 그림사이즈 10,5
# 차트 제목 'scatter plot mpg VS. weight'

# 버블차트 그리기
# 버블차트를 그리기 위해 cylinder 개수의 상대적 비율을 계산하여 시리즈 생성
# cylinder_size = df.cylinders / df.cylinders.max() * 300
# 산점도 그리기 (cylinder 크기 이용), 투명도 0.3
# 차트 제목 'scatter plot : mpg-weight-cylinders'

# 3개의 변수로 산점도 그리기
# 산점도 그리기 (cylinder 크기 이용), 투명도 0.3, 크기 50
# +마커, 오른쪽 네모 박스 색 지정

# count열 추가 : 값은 1
# origin 고유의 값의 합만 뽑기 (origin별로 각 열의 합 구하기)
# 새로운 데이터프레임으로 만들고 인덱스는 'USA', 'EU', 'JAPAN'로 지정

# count열의 파이 차트 그리기
# 그림사이즈 7,5, 값 표시는 소수점 첫째자리 %로 표시
# 파이조각을 나는 시작 점 (각도 표시) 10
# 색 지정
# 차트 제목 'Model origin', 크기 20
# 파이 차트의 비율을 같게(원에 가깝게) 조정 (원의 형태를 유지할 수 있도록)
# 범례는 인덱스가 표시되게, 위치는 오른쪽 위에

# box plot
# 그림 사이즈 가로 15인치, 세로 5인치 지정
# 2개 그래프 그리기
# 1. origin 별로 mpg 박스플롯
# 2. 박스플롯 옆으로 그리기
# 차트 제목 1. 제조국가별 연비분포(수직박스) / 2. 제조국가별 연비분포(수평박스)

# 시도별 전출입 인구수 데이터 불러오기
# engine = "openpyxl"
# 행 열의 개수, 정보, 기술통계 확인
# 결측값 앞의 값으로 채워넣기

# 서울에서 다른 지역으로 이동한 데이터만 추출
# 전출지별 열 삭제
# 전입지별 -> 전입지로 열이름 변경
# 전입지 열을 인덱스로 지정

# 서울에서 경기도로 이동한 인구 데이터 값만 선택

# 해당 데이터 그래프
# matplotlib 이용한 간단한 그래프 그리기
# 그림 사이즈 가로 12인치, 세로 6인치 지정
# 동그란 마커, 사이즈 10으로 그래프 그리기
# 차트 제목 추가 '서울 -> 경기 인구 이동'
# 축의 이름 지정하고 크기는 10으로
# x축 - 기간 / y축 - 이동인구수
# x축 눈금라벨 사이즈 10, 90도 회전
# y축 범위 5000~800000
# 범례 : '서울 -> 경기' 글씨 사이즈 25, 최적의 위치
# 주석 표시
# 주석 1 : "인구이동증가(1970-1995)" , 위치 기준점 10, 400000, 크기 20
# 주석 2 : "인구이동감소(1995-2017)" , 위치 기준점 40, 400000, 크기 20
# 변경사항을 저장하고 그래프로 출력

# 그림 사이즈 가로 10인치, 세로 10인치 지정
# 2개 그래프 그리기
# 1. 동그란 마커, 사이즈 10
# 2. 세모난 마커, 마커 색 그린, 사이즈 15, 선 색 올리브, 
# 선 굵기 4, 범례에 표시되는 서울-> 경기
# 범례 위치 최적
# 2개 그래프 y축 범위 지정 50000~800000
# x축 내용 표시, 75도 회전

# 서울에서 '충청남도', '경상북도', '강원도', '전라남도'로 이동한 인구데이터 값만 선택
# 그래프 테마 ggplot으로 지정
# 그림 사이즈 가로 20인치, 세로 5인치 지정
# 한 도화지에 4개 그래프 겹쳐서 그리기
# 동그란 마커, 크기 10, 선 굵기 2, 색 지정, 범례에 표시되는 서울 -> 00
# 범례 최적의 위치에 나오게
# 그래프 제목 '서울->충남, 경북, 강원, 전남 인구이동', 크기 20
# x축 - 기간 / y축 - 이동인구수
# x축 눈금라벨 90도 회전

# 그림 사이즈 가로 20인치, 세로 10인치 지정
# 4등분 해서 각자 한개씩 나오게

# 데이터 행과 열 서로 바꾸기
# 인덱스를 정수형으로 변경
# 면적그래프 그리기
# 선 그래프 누적되지 않고 서로 겹치도록, 투명도 0.2, 그림사이즈 20,10
# 그래프 제목 '서울 -> 타도시인구이동' 크기 25
# x축 - 기간 / y축 - 이동인구수 크기 15
# 범례 최적의 위치, 크기 15

# bar 그래프
# 그림 사이즈 20, 10 / 막대 사이 공간 0.7 / 색 지정
# 그래프 제목 '서울 -> 타도시인구이동' 크기 25
# x축 - 기간 / y축 - 이동인구수 크기 15
# 범례 최적의 위치, 크기 15

# 데이터 행과 열 서로 바꾸기
# 합계 열 만들기 (값은 행의 합)
# 합계의 가장 큰 값부터 정렬

# barh 그래프
# 그림 사이즈 10, 5 / 막대 사이 공간 0.5 / 색 지정
# 그래프 제목 '서울 -> 타도시인구이동' 크기 20
# x축 - 이동인구수 / y축 - 전입지 크기 15

# 남북한발전전력량 데이터 불러오기
# 북한 데이터만 가져오기
# 인덱스를 발전 전력별로 변경
# 행과 열 서로 바꾸기
# 열이름 변경 / 합계 -> 총발전량
# 총발전량(전년) 열 추가 , 값은 전년도 총발전량
# 증감율 열 추가, 값은 계산 (파생변수)

# 2축 그래프 그리기
# 1. 수력, 화력 누적해서 그림사이즈 20,10 / 사이공간 0.7 인 bar그래프 그리기
# 2. x 인덱스, y 증감율 그래프 그리기
# 선 스타일 --, 동그란 마커, 크기 20, 색 그린, 범례 표시 "전년대비 증감율"
# 1. x축 - 연도 , y축 - 발전량(억 Kwh)
# 2. y축 - 전년대비 증감율
# 범례 위치 : 왼쪽 상단

# Seaborn
# 타이타닉 데이터 불러오기

# regplot
# 그림 사이즈 15,5
# 2개 그래프 그리기 x-age / y=fare
# 1. 선형 회귀선 표시
# 2. 선형 회귀선 미표시

# scatter
# 그림 사이즈 15,5
# 2개 그래프 그리기 x-class / y=fare
# 1. 데이터의 분산 미고려
# 2. 데이터의 분산 고려 (중복X)

# bar plot
# 그림 사이즈 15,5
# 3개 그래프 그리기 x-sex / y=survived
# 1. 기본
# 2. class 별로 쪼개기
# 3. class 별로 쪼개되 누적으로 보이게

# count plot - 빈도 그래프
# 그림 사이즈 15,5
# 3개 그래프 그리기 x-class
# 1. 기본
# 2. who 별로 쪼개기
# 3. who 별로 쪼개되 누적으로 보이게

# boxplot
# 그림 사이즈 15,5
# 2개 그래프 그리기 x-alive, y-age
# 1. 기본
# 2. sex 별로 쪼개기

# violinplot - 바이올린그래프
# 그림 사이즈 15,5
# 2개 그래프 그리기 x-alive, y-age
# 1. 기본
# 2. sex 별로 쪼개기

# join plot : 산점도 + 히스토그램
# 그림 사이즈 15,10
# 4개 그래프 그리기 x-fare, y-age
# 1. 기본
# 2. 회귀선
# 3. 육각 산점도
# 4. 커널 밀집 그래프

# flights 데이터 불러오기
# 행 month 열 year 값 passengers 로 피벗 돌리기
# 그림 사이즈 10,8
# 차트 제목 '연도, 월별 승객수에 대한 Heatmap'

# 히트맵 그리기
# 각 셀의 값 표기
# 값의 데이터 형태 정수형
# 셀 사이 선 굵기 1

# iris 데이터 불러오기
# 관계그래프 그리기
# species 별로 쪼개기